car_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_column_link1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_column_link1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_column_link2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_column_link2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_column_link3_controller:
    type: effort_controllers/JointPositionController
    joint: joint_column_link3
    pid: {p: 100.0, i: 0.01, d: 10.0}
